name: Java CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 15, 16, 17-ea ]
      fail-fast: false
    name: JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Integration Tests
        run: mvn clean test -P errorprone
      - name: Remove Unused Cache
        run: |
          sudo find ~/.m2 ! -neweraa /var/oss-test -iname '*.pom' | while read pom; do parent=`dirname "$pom"`; rm -Rf "$parent"; done
